// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID          int64
	Date        pgtype.Date
	Description string
	AmountOut   pgtype.Int8
	AmountIn    pgtype.Int8
	Currency    string
	Bank        pgtype.Text
}
