// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	GetAllTransactions(ctx context.Context) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
