// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTransaction = `-- name: AddTransaction :one
INSERT INTO transactions (date, description, amount_out, amount_in, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, date, description, amount_out, amount_in, currency
`

type AddTransactionParams struct {
	Date        pgtype.Date
	Description string
	AmountOut   pgtype.Int8
	AmountIn    pgtype.Int8
	Currency    string
}

func (q *Queries) AddTransaction(ctx context.Context, arg AddTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, addTransaction,
		arg.Date,
		arg.Description,
		arg.AmountOut,
		arg.AmountIn,
		arg.Currency,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.AmountOut,
		&i.AmountIn,
		&i.Currency,
	)
	return i, err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT id, date, description, amount_out, amount_in, currency FROM transactions
`

func (q *Queries) GetAllTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountOut,
			&i.AmountIn,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
