// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateTransactionsBatch implements pgx.CopyFromSource.
type iteratorForCreateTransactionsBatch struct {
	rows                 []CreateTransactionsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTransactionsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTransactionsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Date,
		r.rows[0].Description,
		r.rows[0].Amount,
		r.rows[0].Currency,
		r.rows[0].Bank,
		r.rows[0].Category,
	}, nil
}

func (r iteratorForCreateTransactionsBatch) Err() error {
	return nil
}

func (q *Queries) CreateTransactionsBatch(ctx context.Context, arg []CreateTransactionsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"date", "description", "amount", "currency", "bank", "category"}, &iteratorForCreateTransactionsBatch{rows: arg})
}
