// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    date, description, amount, currency, bank, category
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, date, description, amount, currency, bank, category, created_at, updated_at
`

type CreateTransactionParams struct {
	Date        pgtype.Date
	Description string
	Amount      int64
	Currency    string
	Bank        string
	Category    pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Date,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Bank,
		arg.Category,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Bank,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateTransactionsBatchParams struct {
	Date        pgtype.Date
	Description string
	Amount      int64
	Currency    string
	Bank        string
	Category    pgtype.Text
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, date, description, amount, currency, bank, category, created_at, updated_at FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Bank,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, date, description, amount, currency, bank, category, created_at, updated_at FROM transactions
ORDER BY date DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Bank,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET date = $2,
    description = $3,
    amount = $4,
    currency = $5,
    bank = $6,
    category = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, date, description, amount, currency, bank, category, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          int32
	Date        pgtype.Date
	Description string
	Amount      int64
	Currency    string
	Bank        string
	Category    pgtype.Text
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Bank,
		arg.Category,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Bank,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
